### ISSUE TITLE
Why don't you inherits from QCheckbox class

### ISSUE THREAD

**Issue by mbsanchez** [thibDev/qtCustomPlugins#1]
I like this plugin, but i'm wondering, why you inherits from QWidgets, instead of a more natural class as QCheckbox?

**Comment by ThiBsc** [comment]
I use a QWidget to fully manage my layout, but I think it's also possible to do with your solution. It's a possible improvement. If you want to help me to improve this plugin, it's with a great pleasure :)

**Comment by ThiBsc** [comment]
@mbsanchez, I have done this improvement, I push it soon ;)
